name: Build

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Build Docker image'
        run: docker build -t hyperstyle-analysis-prod .

      - name: 'Build project'
        run: docker exec hyperstyle-analysis-prod poetry build

      - name: 'Run tests'
        run: docker exec hyperstyle-analysis-prod poetry run pytest -vv
