name: Docker release

on: [ workflow_dispatch ]

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Space registry
        uses: docker/login-action@v2
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_REGISTRY_USERNAME }}
          password: ${{ secrets.SPACE_REGISTRY_PASSWORD }}

      - name: Fetch project version
        run: echo "DOCKER_TAG=$(grep -m 1 version pyproject.toml | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d ' ' -f 3)" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.jetbrains.team/p/code-quality-for-online-learning-platforms/hyperstyle-utilities/hyperstyle-utilities:$DOCKER_TAG
